//! quack-rl: where the pilot (`quack_nav::rlnav`) learns.
//!
//! - [`calib`] — the simulator's numbers, the paper twin's by default,
//!   fitted to the duck's traces by `rl_calib`.
//! - [`world`] — a house as boxes, posts, holes and things that move; the
//!   depth sensor's rays in it.
//! - [`scenarios`] — houses generated by the thousand, each with what the
//!   map does not know: things on the floor, pets and feet crossing,
//!   doorways and passages beside a hole, low furniture, a map a little off.
//! - [`body`] — the simulated duck as a `quack_nav::explore::Body`: the
//!   journey that runs on it is quack-navd's own loop.
//! - [`field`] — the true distance to the goal, for the reward and the
//!   expert; [`expert`] — the teacher that sees the truth.
//! - [`episode`] — one journey: a scenario, a body, a brain; the reward.
//! - [`brains`] — reckless brains, for the shields.
//!
//! Binaries: `rl_env` (the trainer's environment, over a pipe), `rl_eval`
//! (the bench: the stick against a pilot, scenario by scenario, through the
//! real loop) and `rl_calib` (the simulator fitted to the duck's traces).

pub mod body;
pub mod brains;
pub mod calib;
pub mod episode;
pub mod expert;
pub mod field;
pub mod scenarios;
pub mod world;

/// xorshift64: deterministic per seed, as the paper twin's.
#[derive(Debug, Clone)]
pub struct Rng(pub u64);

impl Rng {
    pub fn new(seed: u64) -> Self {
        Self(seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) | 1)
    }
    pub fn next(&mut self) -> f64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        (self.0 >> 11) as f64 / (1u64 << 53) as f64
    }
    pub fn gauss(&mut self) -> f64 {
        let (u, v) = (self.next().max(1e-12), self.next());
        (-2.0 * u.ln()).sqrt() * (std::f64::consts::TAU * v).cos()
    }
    pub fn range(&mut self, lo: f64, hi: f64) -> f64 {
        lo + (hi - lo) * self.next()
    }
    pub fn chance(&mut self, p: f64) -> bool {
        self.next() < p
    }
    pub fn pick(&mut self, n: usize) -> usize {
        ((self.next() * n as f64) as usize).min(n.saturating_sub(1))
    }
}

pub fn wrap(a: f64) -> f64 {
    (a + std::f64::consts::PI).rem_euclid(std::f64::consts::TAU) - std::f64::consts::PI
}

pub fn dist(a: (f64, f64), b: (f64, f64)) -> f64 {
    (a.0 - b.0).hypot(a.1 - b.1)
}
